### PR TITLE
Reminder of workshop expectations

### LINKED ISSUE #198: Remind folks of CoC in part 2
Suggestion from the 2nd pilot that we remind people of the CoC and hand raising when we return for part 2 (days 5&6)

### PR DESCRIPTION
**Pull request by sstevens2**
Fixes #198

### CODE REVIEW

**Comment by tobyhodges** [comment]
Thanks @sstevens2, this looks good.

Please could you move the CoC link reference to `links.md`, and update the link in `introduction.md` https://github.com/carpentries/lesson-development-training/blob/67d41db8407b5a19f0351e80dc50144cd6df90dd/episodes/introduction.md?plain=1#L69 to also point at the same?

**Comment by sstevens2** [comment]
Thanks Toby!  Knew there must be someway to do that but I'm always uncertain about relative links in these contexts.  Appreciate the clarification.

**Comment by sstevens2** [comment]
Something I'm still unclear on, do I need to have something the references the `links.md` at the bottom of each page or will it know to look for links in the `links.md` file?

**Comment by sstevens2** [comment]
@tobyhodges Let me know if the new sets of links seems right.  They should all be to the relative ../CODE_OF_CONDUCT.md through `links.md`

**Comment by tobyhodges** [comment]
> Something I'm still unclear on, do I need to have something the references the `links.md` at the bottom of each page or will it know to look for links in the `links.md` file?

the references in `links.md` can be used "like magic" i.e. they are made available to all episode files automatically.

**Comment by tobyhodges** [comment]
Thanks @sstevens2 what you've done is exactly what I had in mind. I had not anticipated that it would cause a conflict due to the linkref `[coc]` already being used in the `CODE_OF_CONDUCT.md` file itself. That's leading to this warning in the lesson build:

```
Duplicate link reference '[coc]' at /var/folders/rj/3gf6c_l166qc7fl3z_v4pbxw0000gr/T//RtmpE3s5YD/filee4ec19c6f7b7.md line 18 column 1
```

I think we need to adjust the linkref in `links.md` to point directly to the CoC page in the handbook (https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html) and remove the reference from `CODE_OF_CONDUCT.md`. Sorry for the confusion: this is my fault for being too picky!

**Review by tobyhodges — APPROVED** [review]
Thanks for persevering, @sstevens2 🙌

**Pull request merged**
