### PR TITLE
Initial draft of 'collaborating with newcomers' episode

### PR DESCRIPTION
**Pull request by anenadic**
Initial draft of 'collaborating with newcomers' episode is ready to review. My initial thoughts are that some of the things mentioned (such as issue labelling, mentions, and making progress) are not specific to newcomers and will have to be repeated in the next episode "collaborating with people you know" too. So I tried in this episode to give the things a "newcomer" angle as much as possible, and then we can expand in the next episode. Interested to hear other thoughts.

### CODE REVIEW

**Comment by tobyhodges** [comment]
Thanks Aleks, my local build looks good but the diff on this PR is enormous - see @zkamvar's comment above about `gh-pages` getting merged into your branch. Once that commit is reverted, I'll be very happy to review and provide specific comments.

**Comment by anenadic** [comment]
Hi @tobyhodges @zkamvar,

Not sure what happened and how the branch got into the state that it did - I think there may have been some changes in gh-pages since I started working on my branch so I may have merged them into my branch to make sure I've got everything up to dat. I only ever committed one file though. I'll see what I can do to resolve this.

**Comment by anenadic** [comment]
Looking at the commits - most of them come from an "actions-user" before I even started working on this. I really have no idea what happened here 😆 .

**Comment by tobyhodges** [comment]
@anenadic the difference here, compared to lessons using the previous template, is that you should pull changes from `main` rather than `gh-pages` to keep your branch up-to-date, and create pull requests to `main` too. `sandpaper`, one of the tools in the Workbench, automatically converts (R)Markdown files it finds in `main` into HTML files, which it then commits to `gh-pages`, so that they can be served by GitHub Pages.

**Comment by anenadic** [comment]
Thanks to @tobyhodges we now know what went wrong - I was working off gh-pages instead of the main branch. I have created a new clean branch and a separate PR #21 to replace this one. Will close and delete this branch.

**Comment by zkamvar** [comment]
I'm glad y'all were able to resolve this while I slumbered! For posterity, I want to point out that this issue is the result of a combination of factors:

1. github didn't allow custom page domains until very recently.
2. the styles repository was initially built with this limitation in mind, so the default branch was always set to gh-pages and there often was no "main" branch

Because of these, anyone who worked on carpentries lessons (aside from R-based lessons), would have a strong association of gh-pages as the default branch for working on lessons in git, so this shift to using the main branch will seem odd.

Thank you both again for resolving the problem. I can not see the screenshot that was posted, but I'm wondering if there is any kind of alert I can issue that can prevent this kind of thing from happening?

**Comment by anenadic** [comment]
Maybe a note in the readme to warn/remind people that the main project development branch is `main` rather than `gh-pages` as I came with the exact assumption you mentioned @zkamvar having worked using the old lesson template.

**Pull request closed without merging**
