### PR TITLE
Add showing GitHub Actions to lesson explicitly

### LINKED ISSUE #241: In Carpentries Workbench episode, specifically point out Actions tab
I've found that being able to show that the reason that the changes aren't immediately reflected is because the page is being built behind the scenes. Without diving too much into the weeds, seeing the gears moving and the status color change from yellow to green is satisfying too. GitHub Page builds just break from unknown reasons all the time (or known - YAML formatting issues), so it's good to be able to point to a specific error on why a change wasn't implemented.

### PR DESCRIPTION
**Pull request by sstevens2**
Fixes #241 

First try at incorperating the GitHub actions mention directly in the lesson.

### CODE REVIEW

**Comment by sstevens2** [comment]
Can't add you as a reviewer @MikeTrizna but would really appreciate your review as well.

**Review by anenadic — APPROVED** [review]
Approving this - @sstevens2 and I had a discussion yesterday on where best to place these updates and this PR addresses that perfectly.

**Comment by sstevens2** [comment]
Will wait a little longer to hear if @MikeTrizna has any feedback before merging.

**Comment by MikeTrizna** [comment]
Looks good to me!

**Pull request merged**
